image: docker:latest

stages:
  - build
  - test
  - deploy

variables:
  DOCKER_HOST: unix:///var/run/docker.sock

before_script:
  - apk add --no-cache docker-cli docker-cli-compose curl

build:
  stage: build
  script:
    - docker compose build

test:
  stage: test
  script:
    - docker compose up -d
    - sleep 10
    - docker compose ps
    - docker exec docker-compose-server-1 curl http://localhost:5050
    - docker exec docker-compose-client-1 curl http://localhost:8080
    #- curl http://localhost:8080 || docker compose logs && exit 1
    #- curl http://localhost:5050 || docker compose logs && exit 1
    - docker compose down

deploy:
  stage: deploy
  script:
    - docker compose up -d
  only:
    - main

