image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""

before_script:
  - apk add --no-cache docker-compose curl

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker-compose build

test:
  stage: test
  script:
    - docker-compose up -d
    - sleep 10
    - curl http://localhost:8080 || (docker-compose logs && exit 1)
    - curl http://localhost:5050 || (docker-compose logs && exit 1)
    - docker-compose down

deploy:
  stage: deploy
  script:
    - docker-compose up -d  # or scp to another machine if needed
  only:
    - main

