version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "5050:5050"  # Access server from localhost:5050
    volumes:
      - ./server:/app
    working_dir: /app
    command: python app.py

  client:
    build: ./client
    ports:
      - "8080:8080"  # Expose client on localhost:8080
    volumes:
      - ./client:/app
    working_dir: /app
    command: python app.py
    depends_on:
      - server
    environment:
      SERVER_HOST: server
      SERVER_PORT: 5050

